(define (sum-of-squares-of-largest-2 x y z)
  (if (> x y) 
      (sum-of-squares x (largest y z))
      (sum-of-squares y (largest x z))))
(define (largest x y)
  (if (> x y) x y))
(define (sum-of-squares x y)
  (+ (square x) (square y)))
(define (square x)
  (* x x))