(define (sum-of-squares-of-largest-2 x y z)
  (sum-of-squares (largest x y z) (next-largest x y z)))
(define (largest x y z) 
  (cond ((and (>= x y) (>= x z)) x)
        ((and (>= y x) (>= y z)) y)
        (else z)))
(define (next-largest x y z)
  (cond ((and (< x y) (>= x z)) x)
        ((and (< y z) (>= y x)) y)
        (else z)))
(define (sum-of-squares x y)
  (+ (square x) (square y)))
(define (square x)
  (* x x))